# generated by datamodel-codegen:
#   filename:  workdir/eks_aws_upbound_io_v1beta1_nodegroup.yaml

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class DeletionPolicy(Enum):
    Orphan = 'Orphan'
    Delete = 'Delete'


class Resolution(Enum):
    Required = 'Required'
    Optional = 'Optional'


class Resolve(Enum):
    Always = 'Always'
    IfNotPresent = 'IfNotPresent'


class Policy(BaseModel):
    resolution: Optional[Resolution] = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Optional[Resolve] = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ClusterNameRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class ClusterNameSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class LaunchTemplateItem(BaseModel):
    id: Optional[str] = None
    """
    Identifier of the EC2 Launch Template. Conflicts with name.
    """
    name: Optional[str] = None
    """
    Name of the EC2 Launch Template. Conflicts with id.
    """
    version: Optional[str] = None
    """
    EC2 Launch Template version number. While the API accepts values like $Default and $Latest, the API will convert the value to the associated version number (e.g., 1). Using the default_version or latest_version attribute of the aws_launch_template resource or data source is recommended for this argument.
    """


class NodeRoleArnRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class NodeRoleArnSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class SourceSecurityGroupIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class SourceSecurityGroupIdSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class RemoteAcces(BaseModel):
    ec2SshKey: Optional[str] = None
    """
    EC2 Key Pair name that provides access for remote communication with the worker nodes in the EKS Node Group. If you specify this configuration, but do not specify source_security_group_ids when you create an EKS Node Group, either port 3389 for Windows, or port 22 for all other operating systems is opened on the worker nodes to the Internet (0.0.0.0/0). For Windows nodes, this will allow you to use RDP, for all others this allows you to SSH into the worker nodes.
    """
    sourceSecurityGroupIdRefs: Optional[List[SourceSecurityGroupIdRef]] = None
    """
    References to SecurityGroup in ec2 to populate sourceSecurityGroupIds.
    """
    sourceSecurityGroupIdSelector: Optional[SourceSecurityGroupIdSelector] = None
    """
    Selector for a list of SecurityGroup in ec2 to populate sourceSecurityGroupIds.
    """
    sourceSecurityGroupIds: Optional[List[str]] = None
    """
    Set of EC2 Security Group IDs to allow SSH access (port 22) from on the worker nodes. If you specify ec2_ssh_key, but do not specify this configuration when you create an EKS Node Group, port 22 on the worker nodes is opened to the Internet (0.0.0.0/0).
    """


class ScalingConfigItem(BaseModel):
    desiredSize: Optional[float] = None
    """
    Desired number of worker nodes.
    """
    maxSize: Optional[float] = None
    """
    Maximum number of worker nodes.
    """
    minSize: Optional[float] = None
    """
    Minimum number of worker nodes.
    """


class SubnetIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class SubnetIdSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class TaintItem(BaseModel):
    effect: Optional[str] = None
    """
    The effect of the taint. Valid values: NO_SCHEDULE, NO_EXECUTE, PREFER_NO_SCHEDULE.
    """
    key: Optional[str] = None
    """
    The key of the taint. Maximum length of 63.
    """
    value: Optional[str] = None
    """
    The value of the taint. Maximum length of 63.
    """


class UpdateConfigItem(BaseModel):
    maxUnavailable: Optional[float] = None
    """
    Desired max number of unavailable worker nodes during node group update.
    """
    maxUnavailablePercentage: Optional[float] = None
    """
    Desired max percentage of unavailable worker nodes during node group update.
    """


class VersionRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class VersionSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    amiType: Optional[str] = None
    """
    Type of Amazon Machine Image (AMI) associated with the EKS Node Group. See the AWS documentation for valid values.
    """
    capacityType: Optional[str] = None
    """
    Type of capacity associated with the EKS Node Group. Valid values: ON_DEMAND, SPOT.
    """
    clusterName: Optional[str] = None
    """
    –  Name of the EKS Cluster.
    """
    clusterNameRef: Optional[ClusterNameRef] = None
    """
    Reference to a Cluster in eks to populate clusterName.
    """
    clusterNameSelector: Optional[ClusterNameSelector] = None
    """
    Selector for a Cluster in eks to populate clusterName.
    """
    diskSize: Optional[float] = None
    """
    Disk size in GiB for worker nodes. Defaults to 50 for Windows, 20 all other node groups.
    """
    forceUpdateVersion: Optional[bool] = None
    """
    Force version update if existing pods are unable to be drained due to a pod disruption budget issue.
    """
    instanceTypes: Optional[List[str]] = None
    """
    List of instance types associated with the EKS Node Group. Defaults to ["t3.medium"].
    """
    labels: Optional[Dict[str, str]] = None
    """
    Key-value map of Kubernetes labels. Only labels that are applied with the EKS API are managed by this argument. Other Kubernetes labels applied to the EKS Node Group will not be managed.
    """
    launchTemplate: Optional[List[LaunchTemplateItem]] = None
    """
    Configuration block with Launch Template settings. See launch_template below for details. Conflicts with remote_access.
    """
    nodeRoleArn: Optional[str] = None
    """
    –  Amazon Resource Name (ARN) of the IAM Role that provides permissions for the EKS Node Group.
    """
    nodeRoleArnRef: Optional[NodeRoleArnRef] = None
    """
    Reference to a Role in iam to populate nodeRoleArn.
    """
    nodeRoleArnSelector: Optional[NodeRoleArnSelector] = None
    """
    Selector for a Role in iam to populate nodeRoleArn.
    """
    region: str
    """
    Region is the region you'd like your resource to be created in.
    """
    releaseVersion: Optional[str] = None
    """
    –  AMI version of the EKS Node Group. Defaults to latest version for Kubernetes version.
    """
    remoteAccess: Optional[List[RemoteAcces]] = None
    """
    Configuration block with remote access settings. See remote_access below for details. Conflicts with launch_template.
    """
    scalingConfig: Optional[List[ScalingConfigItem]] = None
    """
    Configuration block with scaling settings. See scaling_config below for details.
    """
    subnetIdRefs: Optional[List[SubnetIdRef]] = None
    """
    References to Subnet in ec2 to populate subnetIds.
    """
    subnetIdSelector: Optional[SubnetIdSelector] = None
    """
    Selector for a list of Subnet in ec2 to populate subnetIds.
    """
    subnetIds: Optional[List[str]] = None
    """
    Identifiers of EC2 Subnets to associate with the EKS Node Group. Amazon EKS managed node groups can be launched in both public and private subnets. If you plan to deploy load balancers to a subnet, the private subnet must have tag kubernetes.io/role/internal-elb, the public subnet must have tag kubernetes.io/role/elb.
    """
    tags: Optional[Dict[str, str]] = None
    """
    Key-value map of resource tags.
    """
    taint: Optional[List[TaintItem]] = None
    """
    The Kubernetes taints to be applied to the nodes in the node group. Maximum of 50 taints per node group. See taint below for details.
    """
    updateConfig: Optional[List[UpdateConfigItem]] = None
    """
    Configuration block with update settings. See update_config below for details.
    """
    version: Optional[str] = None
    """
    –  Kubernetes version. Defaults to EKS Cluster Kubernetes version.
    """
    versionRef: Optional[VersionRef] = None
    """
    Reference to a Cluster in eks to populate version.
    """
    versionSelector: Optional[VersionSelector] = None
    """
    Selector for a Cluster in eks to populate version.
    """


class InitProvider(BaseModel):
    amiType: Optional[str] = None
    """
    Type of Amazon Machine Image (AMI) associated with the EKS Node Group. See the AWS documentation for valid values.
    """
    capacityType: Optional[str] = None
    """
    Type of capacity associated with the EKS Node Group. Valid values: ON_DEMAND, SPOT.
    """
    diskSize: Optional[float] = None
    """
    Disk size in GiB for worker nodes. Defaults to 50 for Windows, 20 all other node groups.
    """
    forceUpdateVersion: Optional[bool] = None
    """
    Force version update if existing pods are unable to be drained due to a pod disruption budget issue.
    """
    instanceTypes: Optional[List[str]] = None
    """
    List of instance types associated with the EKS Node Group. Defaults to ["t3.medium"].
    """
    labels: Optional[Dict[str, str]] = None
    """
    Key-value map of Kubernetes labels. Only labels that are applied with the EKS API are managed by this argument. Other Kubernetes labels applied to the EKS Node Group will not be managed.
    """
    launchTemplate: Optional[List[LaunchTemplateItem]] = None
    """
    Configuration block with Launch Template settings. See launch_template below for details. Conflicts with remote_access.
    """
    nodeRoleArn: Optional[str] = None
    """
    –  Amazon Resource Name (ARN) of the IAM Role that provides permissions for the EKS Node Group.
    """
    nodeRoleArnRef: Optional[NodeRoleArnRef] = None
    """
    Reference to a Role in iam to populate nodeRoleArn.
    """
    nodeRoleArnSelector: Optional[NodeRoleArnSelector] = None
    """
    Selector for a Role in iam to populate nodeRoleArn.
    """
    releaseVersion: Optional[str] = None
    """
    –  AMI version of the EKS Node Group. Defaults to latest version for Kubernetes version.
    """
    remoteAccess: Optional[List[RemoteAcces]] = None
    """
    Configuration block with remote access settings. See remote_access below for details. Conflicts with launch_template.
    """
    scalingConfig: Optional[List[ScalingConfigItem]] = None
    """
    Configuration block with scaling settings. See scaling_config below for details.
    """
    subnetIdRefs: Optional[List[SubnetIdRef]] = None
    """
    References to Subnet in ec2 to populate subnetIds.
    """
    subnetIdSelector: Optional[SubnetIdSelector] = None
    """
    Selector for a list of Subnet in ec2 to populate subnetIds.
    """
    subnetIds: Optional[List[str]] = None
    """
    Identifiers of EC2 Subnets to associate with the EKS Node Group. Amazon EKS managed node groups can be launched in both public and private subnets. If you plan to deploy load balancers to a subnet, the private subnet must have tag kubernetes.io/role/internal-elb, the public subnet must have tag kubernetes.io/role/elb.
    """
    tags: Optional[Dict[str, str]] = None
    """
    Key-value map of resource tags.
    """
    taint: Optional[List[TaintItem]] = None
    """
    The Kubernetes taints to be applied to the nodes in the node group. Maximum of 50 taints per node group. See taint below for details.
    """
    updateConfig: Optional[List[UpdateConfigItem]] = None
    """
    Configuration block with update settings. See update_config below for details.
    """
    version: Optional[str] = None
    """
    –  Kubernetes version. Defaults to EKS Cluster Kubernetes version.
    """
    versionRef: Optional[VersionRef] = None
    """
    Reference to a Cluster in eks to populate version.
    """
    versionSelector: Optional[VersionSelector] = None
    """
    Selector for a Cluster in eks to populate version.
    """


class ManagementPolicy(Enum):
    Observe = 'Observe'
    Create = 'Create'
    Update = 'Update'
    Delete = 'Delete'
    LateInitialize = 'LateInitialize'
    field_ = '*'


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class ConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class Metadata(BaseModel):
    annotations: Optional[Dict[str, str]] = None
    """
    Annotations are the annotations to be added to connection secret.
    - For Kubernetes secrets, this will be used as "metadata.annotations".
    - It is up to Secret Store implementation for others store types.
    """
    labels: Optional[Dict[str, str]] = None
    """
    Labels are the labels/tags to be added to connection secret.
    - For Kubernetes secrets, this will be used as "metadata.labels".
    - It is up to Secret Store implementation for others store types.
    """
    type: Optional[str] = None
    """
    Type is the SecretType for the connection secret.
    - Only valid for Kubernetes Secret Stores.
    """


class PublishConnectionDetailsTo(BaseModel):
    configRef: Optional[ConfigRef] = Field(
        default_factory=lambda: ConfigRef.model_validate({'name': 'default'})
    )
    """
    SecretStoreConfigRef specifies which secret store config should be used
    for this ConnectionSecret.
    """
    metadata: Optional[Metadata] = None
    """
    Metadata is the metadata for connection secret.
    """
    name: str
    """
    Name is the name of the connection secret.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Optional[DeletionPolicy] = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: Optional[InitProvider] = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: Optional[List[ManagementPolicy]] = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: Optional[ProviderConfigRef] = Field(
        default_factory=lambda: ProviderConfigRef.model_validate({'name': 'default'})
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    publishConnectionDetailsTo: Optional[PublishConnectionDetailsTo] = None
    """
    PublishConnectionDetailsTo specifies the connection secret config which
    contains a name, metadata and a reference to secret store config to
    which any connection details for this managed resource should be written.
    Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    This field is planned to be replaced in a future release in favor of
    PublishConnectionDetailsTo. Currently, both could be set independently
    and connection details would be published to both without affecting
    each other.
    """


class RemoteAccesModel(BaseModel):
    ec2SshKey: Optional[str] = None
    """
    EC2 Key Pair name that provides access for remote communication with the worker nodes in the EKS Node Group. If you specify this configuration, but do not specify source_security_group_ids when you create an EKS Node Group, either port 3389 for Windows, or port 22 for all other operating systems is opened on the worker nodes to the Internet (0.0.0.0/0). For Windows nodes, this will allow you to use RDP, for all others this allows you to SSH into the worker nodes.
    """
    sourceSecurityGroupIds: Optional[List[str]] = None
    """
    Set of EC2 Security Group IDs to allow SSH access (port 22) from on the worker nodes. If you specify ec2_ssh_key, but do not specify this configuration when you create an EKS Node Group, port 22 on the worker nodes is opened to the Internet (0.0.0.0/0).
    """


class AutoscalingGroup(BaseModel):
    name: Optional[str] = None
    """
    Name of the AutoScaling Group.
    """


class Resource(BaseModel):
    autoscalingGroups: Optional[List[AutoscalingGroup]] = None
    """
    List of objects containing information about AutoScaling Groups.
    """
    remoteAccessSecurityGroupId: Optional[str] = None
    """
    Identifier of the remote access EC2 Security Group.
    """


class AtProvider(BaseModel):
    amiType: Optional[str] = None
    """
    Type of Amazon Machine Image (AMI) associated with the EKS Node Group. See the AWS documentation for valid values.
    """
    arn: Optional[str] = None
    """
    Amazon Resource Name (ARN) of the EKS Node Group.
    """
    capacityType: Optional[str] = None
    """
    Type of capacity associated with the EKS Node Group. Valid values: ON_DEMAND, SPOT.
    """
    clusterName: Optional[str] = None
    """
    –  Name of the EKS Cluster.
    """
    diskSize: Optional[float] = None
    """
    Disk size in GiB for worker nodes. Defaults to 50 for Windows, 20 all other node groups.
    """
    forceUpdateVersion: Optional[bool] = None
    """
    Force version update if existing pods are unable to be drained due to a pod disruption budget issue.
    """
    id: Optional[str] = None
    """
    EKS Cluster name and EKS Node Group name separated by a colon (:).
    """
    instanceTypes: Optional[List[str]] = None
    """
    List of instance types associated with the EKS Node Group. Defaults to ["t3.medium"].
    """
    labels: Optional[Dict[str, str]] = None
    """
    Key-value map of Kubernetes labels. Only labels that are applied with the EKS API are managed by this argument. Other Kubernetes labels applied to the EKS Node Group will not be managed.
    """
    launchTemplate: Optional[List[LaunchTemplateItem]] = None
    """
    Configuration block with Launch Template settings. See launch_template below for details. Conflicts with remote_access.
    """
    nodeRoleArn: Optional[str] = None
    """
    –  Amazon Resource Name (ARN) of the IAM Role that provides permissions for the EKS Node Group.
    """
    releaseVersion: Optional[str] = None
    """
    –  AMI version of the EKS Node Group. Defaults to latest version for Kubernetes version.
    """
    remoteAccess: Optional[List[RemoteAccesModel]] = None
    """
    Configuration block with remote access settings. See remote_access below for details. Conflicts with launch_template.
    """
    resources: Optional[List[Resource]] = None
    """
    List of objects containing information about underlying resources.
    """
    scalingConfig: Optional[List[ScalingConfigItem]] = None
    """
    Configuration block with scaling settings. See scaling_config below for details.
    """
    status: Optional[str] = None
    """
    Status of the EKS Node Group.
    """
    subnetIds: Optional[List[str]] = None
    """
    Identifiers of EC2 Subnets to associate with the EKS Node Group. Amazon EKS managed node groups can be launched in both public and private subnets. If you plan to deploy load balancers to a subnet, the private subnet must have tag kubernetes.io/role/internal-elb, the public subnet must have tag kubernetes.io/role/elb.
    """
    tags: Optional[Dict[str, str]] = None
    """
    Key-value map of resource tags.
    """
    tagsAll: Optional[Dict[str, str]] = None
    """
    A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
    """
    taint: Optional[List[TaintItem]] = None
    """
    The Kubernetes taints to be applied to the nodes in the node group. Maximum of 50 taints per node group. See taint below for details.
    """
    updateConfig: Optional[List[UpdateConfigItem]] = None
    """
    Configuration block with update settings. See update_config below for details.
    """
    version: Optional[str] = None
    """
    –  Kubernetes version. Defaults to EKS Cluster Kubernetes version.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: Optional[AtProvider] = None
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class NodeGroup(BaseModel):
    apiVersion: Optional[str] = 'eks.aws.upbound.io/v1beta1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[str] = 'NodeGroup'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    NodeGroupSpec defines the desired state of NodeGroup
    """
    status: Optional[Status] = None
    """
    NodeGroupStatus defines the observed state of NodeGroup.
    """


class NodeGroupList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[NodeGroup]
    """
    List of nodegroups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """