apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: ks
spec:
  dependsOn:
  - provider: xpkg.upbound.io/upbound/provider-aws-eks
    version: v1.18.3
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    testing
  repository: xpkg.upbound.io/haarchri/ks
  source: github.com/upbound/project-template
